overrides:
  ceph:
    conf:
      osd:
        osd_class_load_list: "*"
        osd_class_default_list: "*"
tasks:
- install:
- ceph:
    fs: xfs
- workunit:
    clients:
      client.0:
        - cls
